using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver;

namespace ICOAppApi.Model
{
    public class ICOMaster
    {
        [BsonId]
        public ObjectId InternalId { get; set; }                // standard BSonId generated by MongoDb
        public String name {get; set;}
        [BsonId]
        public MongoDBRef ICODropsRef { get; set; }
        [BsonId]
        public MongoDBRef ICOTokenDataRef { get; set; }
        [BsonId]
        public MongoDBRef PredictionVCRef { get; set; }
        [BsonId]
        public MongoDBRef ICOStatsRef { get; set; }
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
    }
}
