using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace ICOAppApi.Model
{
    public class ICO
    {
        [BsonId]
        public ObjectId InternalId { get; set; }                // standard BSonId generated by MongoDb
        public string Id { get; set; }                          // external Id, easier to reference: 1,2,3 etc. 
        public string Body { get; set; } = string.Empty;        
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
        public int UserId { get; set; } = 0;
    }
}
