version: "3"
services:
    web:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - mongodb
        links:
            - "mongodb:db"
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
